[package]
name = "leelo-policy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
leelo-sss = { path = "../leelo-sss" }
rand_core = "0.6"
vstd = "=0.0.0-2026-06-14-0213"
zeroize = "1.8"

[dev-dependencies]
rand_chacha = "0.3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(verus_keep_ghost)', 'cfg(verus_only)'] }
